import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';
import AppHeader from '@/components/layout/AppHeader';
import { BG_COLORS } from '@/constants/uiConstants';

const geistSans = localFont({
  src: '../public/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../public/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full w-full'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full`}
      >
        <AppHeader />
        <main className={`${BG_COLORS.DARK} top-[60px] w-full h-full`}>
          {children}
        </main>
      </body>
    </html>
  );
}
